criterion:
  classes_per_batch: 10
  me_max: true
  sharpen: 0.25
  supervised_imgs_per_class: 2
  supervised_views: 1
  temperature: 0.1
  unsupervised_batch_size: 4
data:
  color_jitter_strength: 1.0
  data_seed: null
  dataset: imagenet
  image_folder: CLS-LOC
  label_smoothing: 0.1
  multicrop: 6
  normalize: true
  root_path: /home/unimelb.edu.au/nbloomfield/Desktop/phd-data/imagenet_small/ILSVRC/Data/
  subset_path: imagenet_subsets
  unique_classes_per_rank: true
  unlabeled_frac: 0.98
logging:
  folder: log/imagenet_test
  write_tag: paws
meta:
  copy_data: false
  device: cuda:0
  load_checkpoint: false
  model_name: resnet50
  output_dim: 2048
  read_checkpoint: null
  use_fp16: false
  use_pred_head: false
optimization:
  epochs: 100
  final_lr: 0.064
  lr: 6.4
  momentum: 0.9
  nesterov: false
  start_lr: 0.3
  warmup: 10
  weight_decay: 1.0e-06
